### ISSUE TITLE
densitree

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#12]
check if we can output stuff to densitree - ideally call it directly using a system call

**Comment by MichelleKendall** [comment]
And/or it would be great if the user could easily send a set of trees to TreeAnnotator (comes with BEAST) to generate the MCC tree for the set, with posterior support values on internal nodes.

**Comment by thibautjombart** [comment]
I suspect outputting to nexus should do the trick, but will have to check and try.

**Comment by thibautjombart** [comment]
Done as of 3b5398a2601ec18ae810b0fc2119fc27abf6e539 - now exporting to Nexus format.
Opening directly densitree is not going to work - can't make densitree work on my computer, and there would be a need to have a specific script in the path called 'densitree', containing the right `java -jar ... ` instructions.
