### ISSUE TITLE
WARNING undeclared dependencies

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#19]
* checking for unstated dependencies in examples ... WARNING
'library' or 'require' calls not declared from:
  ‘RColorBrewer’ ‘ggplot2’ ‘rgl’

**Comment by MichelleKendall** [comment]
These packages are used only in the examples sections and I'm afraid I couldn't work out how to avoid this warning. I couldn't find any solutions online, in fact I found people saying they just put up with the warnings, but this seems unsatisfactory! We can always use "dontrun", "donttest" etc. in the examples to get rid of the warning, but again, it feels like there should be a much better solution.

**Comment by thibautjombart** [comment]
Yes, there will be workarounds. I've had this kind of situations before, will look into it. 
As for warnings, CRAN will reject submissions triggering errors, warnings, or unjustified notes. Policies are listed there:
https://cran.r-project.org/submit.html
more detailed list of instructions:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html

**Comment by thibautjombart** [comment]
Fixed.
