### ISSUE TITLE
Add unit tests using testthat

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#23]
Would be useful to have internal consistency checks, especially for the basic metrics.

**Comment by MichelleKendall** [comment]
I have added various consistency tests for the basic metrics in file testbasics.R

Still to add: more tests for med.tree, and some tests on the expected warnings and errors

**Comment by thibautjombart** [comment]
Cool!

**Comment by MichelleKendall** [comment]
I have added all the tests I can think of, and some warnings in the functions for unexpected inputs etc.

**Comment by MichelleKendall** [comment]
Add tests for findGroves?

**Comment by thibautjombart** [comment]
I'll check

**Comment by thibautjombart** [comment]
This issue should be closed. Adding one specifically for findGroves
