### ISSUE TITLE
Test Rcpp integration

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#24]
I want to make a hello world test to ensure it works.

**Comment by MichelleKendall** [comment]
Yes. I think the answer is here http://dirk.eddelbuettel.com/code/rcpp/Rcpp-package.pdf

I think we need to specify our C++ function in the src directory, as they do, use Rcpp:exports etc. Will come back to it later.

**Comment by thibautjombart** [comment]
Yes, but his is pretty much the old way to integrate C code in a R package.
One of the advantages of Rcpp is not to have to do that. It should be
simpler, although slightly less efficient as every function call will have
compilation overheads.

On Thu, Aug 20, 2015 at 11:03 AM, Michelle Kendall <notifications@github.com

**Comment by MichelleKendall** [comment]
Ah, ok. I have at least got his hello world function working in my fork of the newfeatures branch. Are you saying that if we can do it his way then it will be more efficient? I'm willing to give it a go!

**Comment by thibautjombart** [comment]
Pros/cons:
- `cppFunction`: easier to implement and debug, overhead of compilation
- calling compiled code: faster, compilation done beforehand during package install; bit more cumbersome harder to debug

**Comment by MichelleKendall** [comment]
Ok thanks. Well if I can get it working this way then at least we'll have a working package and we can always improve it later, but I won't waste lots of time on it if it doesn't work soon.

**Comment by MichelleKendall** [comment]
Well that was quick: it's working! :) I'll update all the other functions now so that they call the faster implementation.

**Comment by thibautjombart** [comment]
Awesome. Which way worked?

On Thu, Aug 20, 2015 at 12:01 PM, Michelle Kendall <notifications@github.com

**Comment by MichelleKendall** [comment]
Calling compiled code via the Rcpp::compileAttributes() route

**Comment by thibautjombart** [comment]
Sweet! =D


On Thu, Aug 20, 2015 at 12:07 PM, Michelle Kendall <notifications@github.com

**Comment by thibautjombart** [comment]
I'll merge and run checks now

**Comment by MichelleKendall** [comment]
Argh I broke something when I then ran roxygen2::roxygenise() to update the documentation etc. Sorry.

**Comment by thibautjombart** [comment]
This is now becoming a duplicate of  https://github.com/thibautjombart/treescape/issues/20
Will comment on the other issue and close this one
