### ISSUE TITLE
Write vignette

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#25]
Best to follow what was done in *apex*
https://github.com/thibautjombart/apex

**Comment by thibautjombart** [comment]
@MichelleKendall I will draft a template if you want

**Comment by MichelleKendall** [comment]
That would be really handy, thanks. I should get on to it this afternoon.

**Comment by thibautjombart** [comment]
I've added it. Process is:
 1. change vignettes/treescape.Rmd
 2. compile README.Rmd, which updates both the vignette and the README.md
 3. commit/push to see changes on the landing page

I'm still working on the vignette for now, so shall I email you when I'm done to avoid merging conflicts? Also, as we are moving closer to a CRAN release, @MichelleKendall would you like to be maintainer for the CRAN version?

**Comment by MichelleKendall** [comment]
Great, thanks. Yes please, an email when you've done would be perfect, and yes I'll be the maintainer.

**Comment by thibautjombart** [comment]
Hi Michelle,

I got sidetracked in addition to the interface, so you can go ahead with
the vignette. Will msg if I need to edit it.

**Comment by MichelleKendall** [comment]
Ok, cheers

**Comment by thibautjombart** [comment]
Done. Vignette kicks ass!
da7ffabb260580f87a0788aa9c6dffeeb4412e29
