### ISSUE TITLE
Shiny app bug

### ISSUE THREAD

**Issue by MichelleKendall** [thibautjombart/treescape#28]
Last night it was working great, this morning on both my computers when I try to launch Shiny with treescapeServer(), in R it says

Listening on http://127.0.0.1:3568
Error in radioButtons("treetype", "Type of tree", choices = c("phylogram",  : 
  unused argument (width = "100%")

and in the Shiny window it just says "ERROR: unused argument (width = "100%")" and nothing else.

**Comment by thibautjombart** [comment]
Thanks. Will look into this today. Should be an easy fix. Which version of
shiny are you using?

**Comment by MichelleKendall** [comment]
I'm on version 0.11.1. Cheers.

**Comment by thibautjombart** [comment]
Can you try updating? Current version in R-devel is: 0.12.2
I bet the argument did not exist in your version.

On Thu, Aug 20, 2015 at 10:13 AM, Michelle Kendall <notifications@github.com

**Comment by MichelleKendall** [comment]
Yep that's fixed it! Thanks, and sorry for not realising I wasn't up to date.

**Comment by thibautjombart** [comment]
Cool!
Note, to update all your packages:
update.packages(ask=FALSE)


On Thu, Aug 20, 2015 at 11:01 AM, Michelle Kendall <notifications@github.com

**Comment by MichelleKendall** [comment]
Thanks - done! :)
