### ISSUE TITLE
Ensure camelCase consistency throughout the package

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#39]

**Comment by thibautjombart** [comment]
@MichelleKendall are you happy with this? Motivation is, for some functions, *current.naming.system* does not work as they are seen as S3 methods. For instance, `plot.groves` would be a plot method for the  class *groves*. So I changed to camelCase for some of the functions, but we should be consistent.

**Comment by MichelleKendall** [comment]
Ah, I hadn't realised this distinction. Yes definitely, camelCase throughout sounds very sensible, thanks.

**Comment by thibautjombart** [comment]
Done as of f0de6e6c2a362a4c300309fe53e5dde1043bc883
