### ISSUE TITLE
Implement median tree for clusters

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#41]
Currently, we illustrate the median tree for clusters, but the cluster definition itself is ad-hoc, e.g. in the vignette:
```r
wmCluster1 <- woodmiceTrees[intersect(
   intersect(which(wmx>(-2)),which(wmx<2)),
   intersect(which(wmy>(-2.5)),which(wmy<2.5))
   )]
```
I think we should really avoid this, as people will copy-paste this and wonder why their cluster definitions don't match what they see. For now I'll replace the vignette bit by one using findGroves (will check the example of medTree as well). But for the next version, it may be good to have it readily implemented, e.g. with an argument `group=NULL` by default which will keep current behaviour. 

@MichelleKendall will try to give it a go today.

**Comment by MichelleKendall** [comment]
Ah yes, that was written before findGroves existed. Moving to that would be great, thanks. (And yes it's identical in the example of medTree)

**Comment by thibautjombart** [comment]
Done as of 391c0348949a26d9217f8fe8415285515943ed6e

@MichelleKendall I have changed the output slightly. $median is no longer there because indices lose sense when splitting data by groups. It is replaced by $trees which returns a multiPhylo containing the median tree(s). In practice, syntax is much shorter now. I had to disable a unit test which relied on $median though. Hope it's fine.
