### ISSUE TITLE
rgl dependencies

### ISSUE THREAD

**Issue by MichelleKendall** [thibautjombart/treescape#59]
Support for WebGL has changed. I understand we need to add "rglwidgets" to our Imports. (Check whether it then still passes the check, and if we need to update CRAN)

**Comment by thibautjombart** [comment]
Making updates myself to adegenet and outbreaker.. but I'll track this issue to see how it goes ;)

**Comment by MichelleKendall** [comment]
Great! Full info I received:

To package maintainers using rgl:

Recently I have made a number of improvements to the WebGL support in 
rgl.  These required adding a somewhat long list of package 
dependencies, so I pulled the WebGL support out of rgl and put it in a 
separate package called rglwidget.  Since rgl only uses rglwidget via 
Suggests, users who aren't interested in WebGL won't need to install all 
of those dependencies.

However, your package is one of

  brainR
  grammR
  matlib
  molaR
  pca3d
  pitchRx
  shinyRGL
  treescape

and it appears to need WebGL support.

If you are using it only in a vignette, you can add rglwidgets to 
Suggests, and your users won't be affected.  If you are using it in help 
pages or regular R code, you should add it to Imports.

If you're interested in the new WebGL support, I recommend installing 
rglwidget yourself, and looking at the ?ageControl or ?vertexControl 
help pages.  You could also see a discussion in the later part of a talk 
I just gave, <http://www.stats.uwo.ca/faculty/murdoch/talks/2015-12-02>.

I'm sorry for the inconvenience.

Duncan Murdoch

**Comment by MichelleKendall** [comment]
A quick update so we don't duplicate our efforts: I am now using rglwidgets effectively to display our 3D plots in a better way than previously. I've half-finished making the updates and I'll hopefully be able to commit them tomorrow.

**Comment by MichelleKendall** [comment]
Just awaiting the bug fix promised here before I commit: http://stackoverflow.com/questions/34163627/rglwidget-cannot-replace-previous-3d-plot?newreg=0721fd78baed4d51bf6ac2134133e206

**Comment by MichelleKendall** [comment]
Done
