### ISSUE TITLE
high version numbers 

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treescape#67]
@MichelleKendall 
We need to be careful about version numbers. For some reasons the current version on CRAN is already  1.8.15! 

I am fixing the current issue with vignettes and changing the version number to 1.8.16, as there is no way to backtrack on version numbers unfortunately.

**Comment by MichelleKendall** [comment]
Ah! I had understood that it was good to update the version number with each substantive change. What do you recommend as good practice?

**Comment by thibautjombart** [comment]
Versions usually change upon release. So if we use x.yy.zzz numbering then that means we would have made a few hundreds already.

**Comment by thibautjombart** [comment]
(there's no need to use different version number between releases as that's what commits are for ;) ).

**Comment by MichelleKendall** [comment]
Oops! I had totally misunderstood. Thanks for clarifying, I'll do that from now on.
