### ISSUE TITLE
Allow installation without requiring rgl / windowing system

### ISSUE THREAD

**Issue by hyanwong** [thibautjombart/treescape#69]
I'm trying to install treescape simply to get the KC metric as returned by treeDist. But I'm doing this on a large remote server that doesn't have any windowing system (X11), it seems rather perverse that I should have to install rgl just be be able to calculate a metric. Is there any way I can install and use the treeDist() function without having to install an entire graphical environment?

**Comment by thibautjombart** [comment]
Does this work:
```r
 install.packages("treescape", dependencies = FALSE)
```

**Comment by hyanwong** [comment]
No, see the answer at http://stackoverflow.com/questions/29776802/possible-to-install-a-package-without-installing-dependencies

**Comment by thibautjombart** [comment]
So, as of 7b5acc14270e12b6ba5454030d08810a44b81a03 this should be fixed. I have moved the dependency on RGL from Imports to Suggests, so the package should still be installed without rgl. Note that the server will still need *devtools* and the toolchain to compile code. Lemme know if it works.

Also linking to  https://github.com/thibautjombart/treescape/issues/70 - we need to cut down on deps.

**Comment by hyanwong** [comment]
Thanks, that's really helpful.

**Comment by thibautjombart** [comment]
Is it working? Lemme know so that I can close the issue.

**Comment by hyanwong** [comment]
Hi - just tested on a new user account on the machine and it seems to install fine without rgl, thanks. Haven't tried to see what happens if I run one of the treescape routines that *requires* rgl, but I assume it should fail gracefully.

Thanks for sorting this.

**Comment by thibautjombart** [comment]
As far as I'm concerned, RGL doesn't provide anything essential, just some 3D visualisations. I think the 2d versions (which use adegraphics) are better, as they are by definition optimized for visualisation on a screen.

Great, thanks for the update, closing the issue. 
Best
